---
- name: Render docker-compose.yml
  template:
    src: "{{ guac_files }}/{{ quarter }}/docker-compose.yml.j2"
    dest: "{{ guac_files }}/{{ quarter }}/docker-compose.yml"
    owner: ansible
    group: ansible-admin
    mode: "0660"
  delegate_to: localhost

- name: Render .env
  template:
    src: "{{ guac_files }}/{{ quarter }}/env.quarter.j2"
    dest: "{{ guac_files }}/{{ quarter }}/.env"
    owner: ansible
    group: ansible-admin
    mode: "0660"
  delegate_to: localhost
